version: '3'

services:
  todolist.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:8081"
  todolist.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:8080"
networks:
  default:
    external:
      name: nat

