version: '3'

services:
  todolist.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${TODO_LIST_API_DB}
    ports:
      - "8080:80"
  todolist.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
networks:
  default:
    external:
      name: nat

